### ISSUE TITLE
remove npmRegistry config

### ISSUE THREAD

**Issue by gr2m** [standard-release/app#4]
I don’t think you use that right now?

https://github.com/tunnckoCore/semantic-release-app/blob/5e2a40f6d232d6ff514a73ada957b6f15cf6366e/src/lib/config.js#L11

**Comment by tunnckoCore** [comment]
We [use it here](https://github.com/tunnckoCore/semantic-release-app/blob/5e2a40f6d232d6ff514a73ada957b6f15cf6366e/src/index.js#L178) to get the latest version. Currently just depending on the `dist-tags.latest`.

**Comment by gr2m** [comment]
In that case I would remove dependency on the npm registry and load the last release from GitHub tags. As far as I know, npm@5 also supports semantic versions from GitHub tags.

With a GitHub app we have the opportunity to create a language agnostic solution which has no outside dependencies. Once we have that folks can create a "publish to npm" GitHub app which listens to releases on GitHub, for example.

**Comment by tunnckoCore** [comment]
Hm. Pretty good point. I can try to do it that way when get time again, otherwise PRs are welcome.

> folks can create a "publish to npm" GitHub app

That sounds great, but is impossible. Actually not possible through the npm api, but may be easy to clone the repo and then publish through the folder, hm.

**Comment by gr2m** [comment]
the "publish to npm" GitHub app will need to be able to spawn servers on-demand, similar to how CI services work. It could even utilize sth like Travis, it's basically how semantit-release works today. It will need to create an environment where it can `git clone` the repository and run `npm install` and `npm publish` on it. Nothing that hasn’t been done before :)

**Comment by tunnckoCore** [comment]
Yea, but is too much. It's enough and a lot more easier to just have a package as dependency which will (as SR currently do) publish on CI, no matter which one.

That's why i think that once we did great github app for just releases, we can then remove everything related to that from the SR package, which in turn will just do the npm publishing and redirect users to use them both - the github app and `semantic-release` as devDependency.
